### ISSUE TITLE
Stack slot 0 should also be part of region's SlotParamTable

### ISSUE THREAD

**Issue by vaibhavbsharma** [sohah/VeritestingTransformations#10]
Logging this issue so that we dont lose track of it. 

Stack slot 0 is excluded from the region's table of stack slots (`SlotParamTable`) right now. This is causing issues with veritesting regions inside static methods. For example,

```Java
    public static int simpleRegion(int y) {
        int methodCount = 0;
        if (y != 100)
            methodCount = staticMethod1(y);
        return methodCount;
    }
```
Here the stack slot of `y` is 0 because `simpleRegion` is a static method. But the stack slot 0 is not part of the region's `SlotParamTable`.

**Comment by sohah** [comment]
I have fixed that, but I will leave it for Vaibhav to check and close the issue. I made a new label to the issue to indicate that.

Soha

**Comment by vaibhavbsharma** [comment]
Yes, the new label is useful. Thanks for letting me double-check this issue. It is now fixed! 👍
