### ISSUE TITLE
Higher order regions should not be on only static methods

### ISSUE THREAD

**Issue by vaibhavbsharma** [sohah/VeritestingTransformations#11]
Currently, higher order regions are created for only static methods. If the object reference for the method is a local variable, the Substitution pass will bring the value of the object reference in. There's nothing stopping us from including the non-static higher order region in, if it is available. Can we please allow non-static higher-order regions ?

**Comment by sohah** [comment]
I just finished pushing up a support for this, in this [commit](https://github.com/sohah/VeritestingTransformations/commit/05123897dc519e9114709c5ed5c65030ac21e26a)
