### ISSUE TITLE
TestAndIte equivalence-check fails

### ISSUE THREAD

**Issue by vaibhavbsharma** [sohah/VeritestingTransformations#13]
Please find the source code for [TestAndIte](https://github.com/sohah/VeritestingTransformations/blob/master/src/examples/TestAndIte.java) equivalence check here and run it using [this JPF configuration file](https://github.com/sohah/VeritestingTransformations/blob/master/src/examples/TestAndIte.jpf). 

Please find my log file here: [TestAndIte.log](https://github.com/sohah/VeritestingTransformations/files/2380953/TestAndIte.log)

The equivalence checker finds that the branch side where the outputs aren't equal is feasible. 

### Disclaimer
Please feel free to stop reading this bug report at this point and investigate this issue on your own. I did some preliminary investigation of it and report my findings below. But, I could be going down the wrong path with my investigation. 

----------
### Preliminary investigation
I ran this example with `symbolic.debug` set to `true`. I used the printed solver output in this file to create the following SMT query:  [test.txt](https://github.com/sohah/VeritestingTransformations/files/2381227/test.txt)

Near the beginning, `@w9$1` is set to equal `in0 + 1` on the line `  (= (bvadd in0 #x00000001) @w9$1)`. 

As we can also see, the input to the veritesting region is in `@w3$1`. The output of the region, `@w9$1` is going to be either `@w3$1 + 1` or `@w3$1 - 1`.  

Since `in0` and `@w3$1` are both unconstrained, the solver can easily set them to different values. I added the assertion `(assert (not (= in0 @w3$1)))` at the end to check if the solver can make the input `in0` unequal to `@w3$1`. If it were never possible for these two variables to be unequal, the solver would report "unsat". Unfortunately, the solver reports "sat" along with a model that shows the value of `in0` can be different from the value of `@w3$1`. 

The integer input to the region should really have been `in0`. In other words, `in0` should have been equal to `@w3$1`. Since there is no clause which establishes this equality, the solver finds a inequivalence. I am guessing this is an issue with input substitution and assigning this issue to Soha.

**Comment by sohah** [comment]
Bug is fixed please check and close. The problem was actually in the input table not populated with the last parameter. Substitution is fine.

Soha

**Comment by vaibhavbsharma** [comment]
Wonderful! I've verified that I can see the input being correctly populated in the SMT formula. Here's the portion of the formula last printed by SPF after the fix. 
```
(bvsge in0 #x80000000)
  (bvsle in0 #x7fffffff)
  (bvsge @w9$5 #x80000000)
  (bvsle @w9$5 #x7fffffff)
  (= (bvsub in0 #x00000001) @w9$5)
  (bvsge @w8$5 #x80000000)
  (bvsle @w8$5 #x7fffffff)
  (bvsge in0 #x80000000)
  (bvsle in0 #x7fffffff)
  (bvsge @w7$5 #x80000000)
  (bvsle @w7$5 #x7fffffff)
  (bvsge b0 #x00000000)
  (bvsle b0 #x00000001)
  (bvsge b1 #x00000000)
  (bvsle b1 #x00000001)
  (bvsge @w9$5 #x80000000)
  (bvsle @w9$5 #x7fffffff)
  (let ((a!1 (or (= b0 #x00000000)
                 (and (not (= b0 #x00000000)) (= b1 #x00000000)))))
    (and (= @w8$5 (bvsub in0 #x00000001))
         (= @w7$5 (bvadd in0 #x00000001))
         (or (and (= #x00000000 #x00000000) a!1 (= @w9$5 @w8$5))
             (and (= #x00000000 #x00000000) (not a!1) (= @w9$5 @w7$5)))))
  (bvsge b0 #x00000000)
  (bvsle b0 #x00000001)
  (= b0 #x00000000))
```
We can see that now that the veritesting formula now uses `in0` as the input to the region. Previously, it used `@w3$1` as the input which was a unconstrainted symbolic variable different from `in0`.
