### ISSUE TITLE
arrayload  is resolved for symbolic index

### ISSUE THREAD

**Issue by sohah** [sohah/VeritestingTransformations#14]
We have an issue during array transformation, we are trying so substitute for array load of a symbolic index.

This is the example that we have where both index and length are symbolic:
```
public int boundedOutRangeloadArrayTC(int index, int length) throws ArrayIndexOutOfBoundsException {
        int[] x = {300};
        int temp = 0;
        int y = 2;
        if (length > 0) {
            temp = x[index];
        } else {
            temp = 2;
        }

        if (temp != 0)
            y = 1;
        else
            y = 0;
        return y;
    }

```
Before array transformation we have this region
```
if ((! (<= length 0 ) )) {
   @w10$1 = 348[index:<Primordial,I>]
} else {
   skip; 
}
@w11$1 := (Gamma !(length<=0) @w10$1 2); 

```
after array transformation we conclude the following region

```
if ((! (<= length 0 ) )) {
   **@w10$1 := 300;** 
} else {
   skip; 
}
@w11$1 := (Gamma !(length<=0) @w10$1 2); 

```

where we actually actually substitute for the array load.

**Comment by sohah** [comment]
Precisely, I think it is happening because of 
`if (index == len-1) return getArrayElement(eiArray, index);` in `constructArrayITE`, but I am not sure why this check needed?

**Comment by vaibhavbsharma** [comment]
I am not sure if I am understanding this bug report correctly. Isn't that post-array transformation summary correct in the nominal aka unexceptional case when the array has only one entry ?

I also changed the array in that example to have another entry with the value `400`. Here's the summary that was produced after the array transformation.
```
if ((! (<= length 0 ) )) {
   @w11$1 := (Gamma index==0 300 400); 
} else {
   skip; 
}
@w12$1 := (Gamma !(length<=0) @w11$1 2); 
```

I can see one problem with this array substitution: it isn't creating a array reference variable using which a later SPF case transformation can figure out that this assignment statement involved a load from an array. Is that the bug you were reporting ?

**Comment by sohah** [comment]
Yes this is exactly it, at that point the region should contain enough information for both nominal and non nominal cases, we can't assume that this is happening only for the nominal case.

**Comment by vaibhavbsharma** [comment]
That's true. Would it be possible for the array transformation to populate an SPF case environment table of some kind with the information required to set up the SPF case ? Later the SPF case transformation can use this new environment table for constructing SPF cases for arrays and fields.

**Comment by sohah** [comment]
Let's talk tomorrow, for I can see also now array transformation changing arrayloads to gammas. We knew this, but somehow it was completely forgot during our discussion today. I have no means to obtain information about the array if it is done in this current sequence of transformation. Let's talk more tomorrow.

**Comment by vaibhavbsharma** [comment]
We've since figured out how to handle SPF cases for array transformations. We create an IfThenElseStmt for every array access where the else-side contains a throw statement and the then-side contains the unexceptional behavior as allowed by the condition in the IfThenElseStmt. 

Is it ok if we close this issue ?

**Comment by sohah** [comment]
done!
