### ISSUE TITLE
Stack Slots for locals Problem

### ISSUE THREAD

**Issue by sohah** [sohah/VeritestingTransformations#16]
We still have a problem in identifying stack slot for locals, our `findLocalsForValueNumbers` is not working in all cases and our fix point for finding slots for phis is not figuring this out. 
Again in the contract discovery project that I am working on, given the example [https://github.com/sohah/ContractDiscovery/blob/3d63d750bf1e78eb5b496ece520f9ecd58c5c594/src/examples/ExtraSimplePad.java](here) with the .jpf file [https://github.com/sohah/ContractDiscovery/blob/3d63d750bf1e78eb5b496ece520f9ecd58c5c594/src/examples/ExtraSimplePad.jpf](here) and the cfg attached to the issue, we weren't able to identify the stack slot of the w26 which is the return value in the local "ignitionSignal".
[ir.pdf](https://github.com/sohah/VeritestingTransformations/files/2431883/ir.pdf)

**Comment by vaibhavbsharma** [comment]
Fixed. Stack slot discovery has improved now (I think) with commits made for [issue 18](https://github.com/sohah/VeritestingTransformations/issues/18). I ran into a couple of minor issues while running ExtraSimplePad that I have fixed too now.
