### ISSUE TITLE
Tasks to do

### ISSUE THREAD

**Issue by vaibhavbsharma** [sohah/VeritestingTransformations#22]
Soha and I met and went over recent changes and issues. Here's a list of things we're going to work on in the immediate future.

1. Add static analysis metrics
    - assigned to Vaibhav
2. Run Siena benchmark for SPF cases
    - assigned to Soha
3. Return statements might be showing up when using higher order regions in replace_5
    - assigned to Soha. Being tracked in [Issue 24](https://github.com/sohah/VeritestingTransformations/issues/24). 
4. Depth of higher order regions should be limited.
    - assigned to Soha
5. Add metrics - assigned to Soha
    - number of  successful higher order regions
    - number of  region instantiations that we gave up on

**Comment by sohah** [comment]
closing this old thread too, all tasks in it are done, we can assign tasks on the refactoring issue to maintain everything in one place.
