### ISSUE TITLE
HigherOrder3 equivalence-check fails

### ISSUE THREAD

**Issue by vaibhavbsharma** [sohah/VeritestingTransformations#26]
[HigherOrder3](https://github.com/sohah/VeritestingTransformations/blob/master/src/examples/HigherOrder3.java) equivalence-check fails. This check calls a method on a derived class object stored with the base class type. SubstitutionVisitor.visit(InvokeInstruction) uses the static type of the call site instead of using the type available during instantiation. This causes the higher order region to include the base class' method summary instead of using the summary from the derived class.

**Comment by sohah** [comment]
Just fixed that, could you please test it and close the issue, thanks!

**Comment by vaibhavbsharma** [comment]
I see that dynamicClassName skips the last character of the class name in this fix. Can you please explain why that is useful ?

**Comment by sohah** [comment]
Yup, the way we construct the key includes the class name only without any special characters. The fix removes ";" from the name of the class, so we'd be able to reconstruct the key and look it up. In our map ";" is not part of the name.

**Comment by vaibhavbsharma** [comment]
This fix does resolve this equivalence-check, so that's good news and enough of a reason to close this issue. 

But, dropping the last character isn't always a good idea because sometimes the classname reported at that point doesn't have a semicolon at the end. I can also see that `dynamicClassName` isn't actually used in `SubstitutionVisitor.findMethodRegion`. Do we need this change ? 

On a different note related to this fix, looking up the Wala variable type from the `varTypeTable` may, at times, give us a non-primitive type inferred during static analysis. This is related to [Issue 27](https://github.com/sohah/VeritestingTransformations/issues/27) where Java Ranger crashes when running replace because it fails to construct class information for java.lang.Object, a type that was reported during static analysis. We need to guard against such incorrect types because it affects the correctness of higher-order regions. Can you please look into this issue too so that we always use most updated type for higher-order region lookup ?

**Comment by vaibhavbsharma** [comment]
Closing this issue because we're tracking our type inference woes as part of Refactoring issues list (https://github.com/sohah/VeritestingTransformations/issues/23).
