### ISSUE TITLE
Incorrect parameter substitution during higher order region inlining

### ISSUE THREAD

**Issue by vaibhavbsharma** [sohah/VeritestingTransformations#30]
I am running into an issue when running Schedule (src/schedule2_3/schedule2_3.jpf). The problem arises from SubstituteGetOutput.executeRead() running into object references that are in the single digits. This is not possible because more than 100 objects are allocated, with each object referenced by an integer 1 more than the previously allocated object, before SPF runs the subject program. 

Something goes wrong when we start inlining methods originating from `Schedule2.block()` in `Schedule2.schedule()`. You can debug multiple instances of this issue by setting a breakpoint at line 85 aka the line that prints 
```
exceptionalMessage = "ElementInfo class reference (" + eiFieldOwner.getClassInfo().getName() +
                                ") does not match FieldInfo class reference (" + fieldInfo.getClassInfo().getName() + ")";
```
in SubstituteGetOutput.java (aka `SubstituteGetOutput.invoke()`).

**Comment by vaibhavbsharma** [comment]
@sohah I believe this issue has been fixed but I am not sure. If you have fixed this issue, please feel free to close it.

**Comment by sohah** [comment]
This issue has been fixed, i'm closing it.
