### ISSUE TITLE
wbs has two execution paths on master

### ISSUE THREAD

**Issue by sohah** [sohah/VeritestingTransformations#31]
I ran wbs on master and I could see wbs ends with 2 execution paths instead of one. I could see that this is the result of "region ends on a stack consuming instruction" exception being raised for one of the regions. The same exception used to exist during our paper submission, not sure what is going on. I am assigning this to myself, because I want to rule out that it is not a static analysis problem. 
To replicate the problem run WBS.mode5.jpf with jitAnalysis turned off.
region with the failure is with key: WBS.update(IZZ)V#107

**Comment by vaibhavbsharma** [comment]
Please feel free to re-test WBS with the latest changes on the master branch and close this issue if it no longer exists.

**Comment by sohah** [comment]
I just tested that, and it is back to one execution path. I'm closing this issue.
