### ISSUE TITLE
Region boundary shouldn't be in terms of integer IDs for Wala variables

### ISSUE THREAD

**Issue by vaibhavbsharma** [sohah/VeritestingTransformations#7]
Here's an example program:
```Java
    public int countBitsSet(int x) {
        int count = 0;
        while (x != 0) {
            if ((x & 1) != 0) {
                count += 1;
            }
            x = x >>> 1; // logical right shift
        }
        return count;
    }
```

Here's its corresponding CFG: 
[ir.pdf](https://github.com/sohah/VeritestingTransformations/files/2367552/ir.pdf)

The region we are interested in veritesting is from BB3 to BB5. The region boundary gets computed as (first-use, last-def) = (6, 8). Due to this, `SlotParamTable.filterTableForBoundary` will delete the stack slots of Wala variables like v11 even though they are inside the region. 

This example breaks our assumption that Wala variable numbers will monotonically increase inside a region.

**Comment by sohah** [comment]
Bug fixed, please check Vaibhav and close.

**Comment by vaibhavbsharma** [comment]
I've verified that we can now see the local variable region boundary for this region range from 6 to 11 in SlotParamTable. Fixed!
